theme: jekyll-theme-chirpy
baseurl: ""
lang: en
plugins:
  - jekyll-target-blank


prefer_datetime_locale:

# timezone: Asia/Calcutta

title: Devcrypted

tagline: Cloud & DevOps Simplified for Everyone!

description: >-
  Cloud & DevOps Simplified for Everyone!

url: "https://devcrypted.com"

github:
  username: devcrypted
twitter:
  username: devcrypted_com
patreon:
  username: devcrypted
instagram:
  username: devcrypted
youtube:
  channelid: UCsV90U2e5FqsSTMizQCH4vA

social:
  name: Devcrypted
  email: devcrypted@outlook.com
  links:
    - https://decrypted.in/github
    - https://decrypted.in/twitter
    - https://decrypted.in/channel
    - https://decrypted.in/linkedin

# Web Analytics Settings
analytics:
  google:
    id: "G-Z0GCE32EN4"
  goatcounter:
    id: # fill in your GoatCounter ID

# theme_mode: dark # [light | dark]

img_cdn: # Will use Cloudflare CDN in future

# the avatar on sidebar, support local or CORS resources
avatar: https://avatars.githubusercontent.com/u/177287932?s=400&u=e777516f3dcc75ae5110c9dc58832bfedb939d03&v=4

# boolean type, the global switch for ToC in posts.
toc: true

comments:
  active: giscus
  giscus:
    repo: aworkaround/aworkaround.github.io
    repo_id: 843727717
    category: Comments
    category_id: 42399003
    mapping: pathname
    input_position: bottom
    lang: en
    reactions_enabled: 1

assets:
  self_host:
    enabled:
    env: # [development|production]

pwa:
  enabled: false
  cache:
    enabled: false
    deny_paths:

paginate: 5

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json
  - archive_old
  - template
  - reference_files
  - kubernetes
  - Dockerfile

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
